name: Arch Linux Test CI

on:
  push:
    branches: [trunk, feature/archlinux-compatibility]

jobs:
  build_latex:
    runs-on: ubuntu-22.04
    container:
      image: archlinux:base-devel
    env:
      DEPENDENCIES: "texlive-science minted"
      JUPYNOTEX_ENV: jupynotex
      FADES_AUR: https://aur.archlinux.org/cgit/aur.git/snapshot/fades.tar.gz
      BUILD_USER: build
      # BUILDDIR: "/tmp"

    steps:
      - uses: actions/checkout@v3
      - name: Install jupynotex and fades
        run: |
          useradd -l -s /bin/bash $BUILD_USER
          echo "${BUILD_USER} ALL=(ALL) ALL" > /etc/sudoers.d/$BUILD_USER
          pacman -Syu --noconfirm && pacman -S $DEPENDENCIES --noconfirm >/dev/null
          chown -R $BUILD_USER:$BUILD_USER .
          su $BUILD_USER -c "curl -LO $FADES_AUR && tar -xvf fades.tar.gz && pushd fades && makepkg -s --noconfirm && popd"
          chown -R root:root .
          ls -l fades
          JUPYNOTEX_PATH=$(kpsewhich -var-value TEXMFDIST)/tex/latex/$JUPYNOTEX_ENV
          echo Files founded over $JUPYNOTEX_PATH [1/2]
          ls -l $JUPYNOTEX_PATH
          echo Patching [2/2]
          mv $JUPYNOTEX_ENV.* $JUPYNOTEX_PATH

      - name: Test
        run: |
          ./run_tests
