name: Arch Linux Test CI

on:
  push:
    branches: [trunk, feature/archlinux-compatibility]

jobs:
  build_latex:
    runs-on: ubuntu-22.04
    container:
      image: archlinux:base
    env:
      JUPYNOTEX_ENV: jupynotex

    steps:
      - uses: actions/checkout@v3
      - name: Install jupynotex
        run: |
          pacman -Syu --noconfirm
          pacman -S texlive-science minted --noconfirm
          ls -l /usr/share/texmf-dist/tex/latex/${JUPYNOTEX_ENV}
          env
